### ISSUE TITLE
I'd like to use your code but I won't do it because of missing license.

### ISSUE THREAD

**Issue by dueddel** [jlattimer/CRMSoapAuthPHP#2]
Hi Jason,

I have a question about the project's license since I am working for a bigger client and I don't like to use code from the internet that isn't clearly licensed with let's say "MIT" or anything similar.

At first I really appreciate what you've done so far. Dynamics CRM web services are pretty hard to deal with if you ask me. But after some adaptions of your code for Symfony2 it works like a charm in my project.

But to break down the small-talk a bit… ;-)

I can't see any license for your code. According to [GitHub Licensing information](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) that means _"nobody else may reproduce, distribute, or create derivative works from your work"_ which is a pity.

I would be happy if you could either add an appropriate license to CRMSoapAuthPHP or if you would explicitly allow me to use and change it a bit for my client project.

Thanks in advance and best regards from Hamburg, Germany!

**Comment by jlattimer** [comment]
Is Apache 2.0 good enough?

**Comment by dueddel** [comment]
It's up to you, I think. ;-) Best is [MIT](https://opensource.org/licenses/MIT), of course. Not sure right now if Apache license is okay for my client's requirements. In the end the choice is yours. :-)

**Comment by jlattimer** [comment]
MIT it is :)

**Comment by dueddel** [comment]
Wonderful! Thanks a lot. :+1:
